keys:
  - &Frederiks-Macbook-Pro age1vv6myqr6f8t594rpe5s24udml7a375zte62swfalnuecgf286fespyajgs
  - &rvn-pc age1f8fyxkldde3wkhlfsccmn72tscr94yhtk34yzqk56d0vmxur6cusuf0208
  - &admin 5E0FEC74518ED5FEAA5EA33E5C49A562D850322A
  - &rvn-vm age1d3cj77x9fpr3epm66l5ff2ptwyv55pf6sh9p5fw7f6ffkseuayqs427r79
  - &rvn-srv age1qvnp38vf03rypemwah5t3khtypkh8tdz2n6rv88eemuuupsv39eqaele9g

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *Frederiks-Macbook-Pro
          - *rvn-pc
          - *rvn-vm
          - *rvn-srv
