keys:
  - &rvn-srv age1u2rhqmpquey2qwdrqmggxtfdf46hv4tlsxywm4yyahf0xnwuy3msa7edup
  - &Frederiks-Macbook-Pro age1pxd5w4wmh7zwgu5xpxew0astg9e9x0nn6u4lltf4hy520z9avd5q5rm5re
  - &rvn-pc age1f8fyxkldde3wkhlfsccmn72tscr94yhtk34yzqk56d0vmxur6cusuf0208
  - &admin 5E0FEC74518ED5FEAA5EA33E5C49A562D850322A
  - &rvn-vm age1d3cj77x9fpr3epm66l5ff2ptwyv55pf6sh9p5fw7f6ffkseuayqs427r79

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *rvn-srv
          - *Frederiks-Macbook-Pro
          - *rvn-pc
          - *rvn-vm
