keys:
  - &admin 5E0FEC74518ED5FEAA5EA33E5C49A562D850322A
  - &rvn-vm age1d3cj77x9fpr3epm66l5ff2ptwyv55pf6sh9p5fw7f6ffkseuayqs427r79

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *rvn-vm
