keys:
  - &Frederiks-Macbook-Pro age1vv6myqr6f8t594rpe5s24udml7a375zte62swfalnuecgf286fespyajgs
  - &Frederiks-Macbook-Pro-system age1pxd5w4wmh7zwgu5xpxew0astg9e9x0nn6u4lltf4hy520z9avd5q5rm5re
  - &rvn-srv age1u2rhqmpquey2qwdrqmggxtfdf46hv4tlsxywm4yyahf0xnwuy3msa7edup
  - &rvn-pc age1v0p4ekm5nqzlxy749radmeufcfqslq4wjveg5dwxmxsg9q7wu4ssavkhm2
  - &rvn-pc-host age1f3kcm8zhfy6jkgfscpamnsyggdswqdqegnaslrawsaqqj4yeraps97my7y
  - &admin 5E0FEC74518ED5FEAA5EA33E5C49A562D850322A
  - &rvn-vm age1d3cj77x9fpr3epm66l5ff2ptwyv55pf6sh9p5fw7f6ffkseuayqs427r79
  - &fbb-user age1qvnp38vf03rypemwah5t3khtypkh8tdz2n6rv88eemuuupsv39eqaele9g

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *Frederiks-Macbook-Pro-system
          - *rvn-srv
          - *rvn-pc
          - *rvn-pc-host
          - *rvn-vm
          - *fbb-user
  - path_regex: secrets/(common|apis|containers|development)\.yaml$
    key_groups:
      - pgp:
          - *admin
        age:
          - *Frederiks-Macbook-Pro
          - *Frederiks-Macbook-Pro-system
          - *rvn-srv
          - *rvn-pc
          - *rvn-pc-host
          - *rvn-vm
          - *fbb-user
