[[packages]]
name = "diff"
cve = "CVE-2024-13278"
comment = "Package name collision: CVE affects Diff-1.0.2, not GNU diffutils in nixpkgs"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2020-8284"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2022-27776"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2022-27781"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2022-27782"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2022-32206"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2022-32221"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2022-35252"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2022-43552"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2023-28319"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2023-28320"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2023-28321"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "curl"
cve = "CVE-2023-28322"
comment = "Version mismatch: CVE affects curl-0.4.46, we use libcurl 8.x"
expiry = "2025-12-31"

[[packages]]
name = "zlib"
cve = "CVE-2022-37434"
comment = "Version mismatch: CVE affects zlib-0.7.1.1, we use zlib 1.3.x"
expiry = "2025-12-31"

[[packages]]
name = "zlib"
cve = "CVE-2023-45853"
comment = "Version mismatch: CVE affects zlib-0.7.1.1, we use zlib 1.3.x"
expiry = "2025-12-31"

[[packages]]
name = "zlib"
cve = "CVE-2023-6992"
comment = "Version mismatch: CVE affects zlib-0.7.1.1, we use zlib 1.3.x"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2020-1171"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2020-1192"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2020-17163"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2021-23336"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2021-3733"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2022-0391"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2022-26488"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2022-45061"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2022-48560"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2022-48564"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2022-48565"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2022-48566"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2023-24329"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2023-36632"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2023-40217"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2024-49050"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2024-6232"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2024-7592"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2024-9287"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "python"
cve = "CVE-2025-49714"
comment = "Python 2.7 is EOL and not in runtime closure, likely build dependency"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2021-35047"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2021-35048"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2021-35049"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2021-35050"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-0486"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-0997"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-24388"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-24389"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-24390"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-24391"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-24392"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-24393"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "network"
cve = "CVE-2022-24394"
comment = "Package name collision: CVE likely affects different network package than Haskell network library"
expiry = "2025-12-31"

[[packages]]
name = "cereal"
cve = "CVE-2020-11104"
comment = "Package name collision: CVE likely affects different cereal package than C++ serialization library"
expiry = "2025-12-31"

[[packages]]
name = "cereal"
cve = "CVE-2020-11105"
comment = "Package name collision: CVE likely affects different cereal package than C++ serialization library"
expiry = "2025-12-31"