{
  flake.modules.nixos.shell =
    { pkgs, ... }:
    {
      environment.shells = [
        pkgs.fish
        pkgs.dash
      ];
    };

  flake.modules.homeManager.shell =
    { config
    , lib
    , pkgs
    , ...
    }:
    let
      requiredSecrets = [
        "github-token"
        "kagi-api-token"
        "openai-api-key"
        "exa-api-key"
        "openmemory-api-key"
      ];
      hasRequiredSecrets = lib.all
        (
          name: lib.hasAttrByPath [ "sops" "secrets" name "path" ] config
        )
        requiredSecrets;
      secretsMap = lib.optionalAttrs hasRequiredSecrets {
          GITHUB_TOKEN = config.sops.secrets.github-token.path;
          COPILOT_TOKEN = config.sops.secrets.github-token.path;
          KAGI_API_TOKEN = config.sops.secrets.kagi-api-token.path;
          OPENAI_API_KEY = config.sops.secrets.openai-api-key.path;
          EXA_API_KEY = config.sops.secrets.exa-api-key.path;
          OPENMEMORY_API_KEY = config.sops.secrets.openmemory-api-key.path;
        };

      readSecrets = lib.concatStringsSep "\n" (
        lib.mapAttrsToList
          (name: path: ''
            if [ -r ${path} ]; then
              ${name}=$(cat ${path})
            else
              echo "Warning: skipping unreadable secret ${name} at ${path}" >&2
              ${name}=""
            fi
          '')
          secretsMap
      );

      fishExports = lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: _: "set -gx ${name} '$" + name + "'") secretsMap
      );
    in
    {
      home.packages = with pkgs; [
        fish
        zsh
        dash
        starship
        zoxide
        atuin
        navi
        tealdeer
      ];

      home.activation.generateFishSecrets = lib.mkIf hasRequiredSecrets (
        lib.hm.dag.entryAfter [ "sops-nix" "setupLaunchAgents" "writeBoundary" ] ''
          $DRY_RUN_CMD mkdir -p ${config.home.homeDirectory}/.config/fish

          ${readSecrets}

          umask 077
          cat > ${config.home.homeDirectory}/.config/fish/private.fish << EOF
          # Auto-generated by Home Manager - secrets loaded at activation time
          ${fishExports}
          EOF

          $DRY_RUN_CMD ${lib.getExe' pkgs.coreutils "chmod"} 600 ${config.home.homeDirectory}/.config/fish/private.fish
        ''
      );
    };
}
