{
  flake.modules.nixos.desktop = { pkgs, ... }: {
    environment.systemPackages = with pkgs; [
      xrdb
      xhost
      xrandr
      xprop
      xwininfo
      xwayland
      xwayland-satellite
      setxkbmap
      wev
      nwg-look
      nwg-displays
      wlr-randr
      wl-clipboard
      xclip
      xsel
      autocutsel
      cliphist
      wl-clip-persist
      wtype
      xdotool
      swaynotificationcenter
      libnotify
      swayosd
      gsettings-desktop-schemas
      awww
    ];
  };
}
